# Generated by Django 5.1.4 on 2025-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_address_user_phone_number_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smartwatch', 'Smartwatch')], max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_condition', models.CharField(max_length=100)),
            ],
        ),
    ]
