# Generated by Django 5.1.4 on 2025-02-19 07:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='products/default.jpg', upload_to=api.models.product_image_upload_path),
        ),
    ]
