# Generated by Django 5.1.4 on 2025-02-25 03:24

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to=api.models.product_image_upload_path)),
                ('back_image', models.ImageField(upload_to=api.models.product_image_upload_path)),
                ('side_image', models.ImageField(upload_to=api.models.product_image_upload_path)),
                ('extra_image', models.ImageField(upload_to=api.models.product_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
    ]
