# Generated by Django 5.1.4 on 2025-03-02 05:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='back_image',
            field=models.ImageField(default='products/default.jpg', upload_to=api.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='extra_image',
            field=models.ImageField(default='products/default.jpg', upload_to=api.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='front_image',
            field=models.ImageField(default='products/default.jpg', upload_to=api.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='side_image',
            field=models.ImageField(default='products/default.jpg', upload_to=api.models.product_image_upload_path),
        ),
    ]
