# Generated by Django 5.1.4 on 2025-03-08 06:41

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productimage_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='back_image',
            field=models.ImageField(upload_to=api.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='extra_image',
            field=models.ImageField(upload_to=api.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='front_image',
            field=models.ImageField(upload_to=api.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='side_image',
            field=models.ImageField(upload_to=api.models.product_image_upload_path),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
