# Generated by Django 5.1.4 on 2025-03-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_productimage_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
