# Generated by Django 5.1.4 on 2025-03-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_order_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
